/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ssben
 */

import javax.swing.JOptionPane;
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        appTitle = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        areaPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        volumePanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        weightPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lengthPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        fromLength = new javax.swing.JComboBox<>();
        toLength = new javax.swing.JComboBox<>();
        jButton10 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        lengthInput = new javax.swing.JTextField();
        speedPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        forcePanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        temperaturePanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        densityPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        energyPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton9.setText("Energy");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton1.setText("Length");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Area");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Weight");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Temperature");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Speed");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Force");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Density");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton3.setText("Volume");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        appTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        appTitle.setText("All Units");

        jLayeredPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Area Converter");

        javax.swing.GroupLayout areaPanelLayout = new javax.swing.GroupLayout(areaPanel);
        areaPanel.setLayout(areaPanelLayout);
        areaPanelLayout.setHorizontalGroup(
            areaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(areaPanelLayout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(jLabel2)
                .addContainerGap(202, Short.MAX_VALUE))
        );
        areaPanelLayout.setVerticalGroup(
            areaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(areaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Volume Converter");

        javax.swing.GroupLayout volumePanelLayout = new javax.swing.GroupLayout(volumePanel);
        volumePanel.setLayout(volumePanelLayout);
        volumePanelLayout.setHorizontalGroup(
            volumePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(volumePanelLayout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jLabel4)
                .addContainerGap(189, Short.MAX_VALUE))
        );
        volumePanelLayout.setVerticalGroup(
            volumePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(volumePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Weight Converter");

        javax.swing.GroupLayout weightPanelLayout = new javax.swing.GroupLayout(weightPanel);
        weightPanel.setLayout(weightPanelLayout);
        weightPanelLayout.setHorizontalGroup(
            weightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(weightPanelLayout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(jLabel3)
                .addContainerGap(190, Short.MAX_VALUE))
        );
        weightPanelLayout.setVerticalGroup(
            weightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(weightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Length Converter");

        jLabel10.setText("Convert From");

        jLabel11.setText("Convert To");

        fromLength.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Meters", "Centimeters", "Millimeters", "Feet", "Inches", "Yards" }));
        fromLength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromLengthActionPerformed(evt);
            }
        });

        toLength.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Meters", "Centimeters", "Millimeters", "Feet", "Inches", "Yards" }));

        jButton10.setText("Convert");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel12.setText("Enter the Length");

        javax.swing.GroupLayout lengthPanelLayout = new javax.swing.GroupLayout(lengthPanel);
        lengthPanel.setLayout(lengthPanelLayout);
        lengthPanelLayout.setHorizontalGroup(
            lengthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lengthPanelLayout.createSequentialGroup()
                .addGroup(lengthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lengthPanelLayout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lengthPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(lengthPanelLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(lengthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(lengthPanelLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(112, 112, 112)
                                .addComponent(toLength, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lengthPanelLayout.createSequentialGroup()
                                .addGroup(lengthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(lengthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fromLength, 0, 150, Short.MAX_VALUE)
                                    .addComponent(lengthInput))))))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        lengthPanelLayout.setVerticalGroup(
            lengthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lengthPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(lengthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lengthInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lengthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(fromLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lengthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Speed Converter");

        javax.swing.GroupLayout speedPanelLayout = new javax.swing.GroupLayout(speedPanel);
        speedPanel.setLayout(speedPanelLayout);
        speedPanelLayout.setHorizontalGroup(
            speedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(speedPanelLayout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(jLabel5)
                .addContainerGap(195, Short.MAX_VALUE))
        );
        speedPanelLayout.setVerticalGroup(
            speedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(speedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Force Converter");

        javax.swing.GroupLayout forcePanelLayout = new javax.swing.GroupLayout(forcePanel);
        forcePanel.setLayout(forcePanelLayout);
        forcePanelLayout.setHorizontalGroup(
            forcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forcePanelLayout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(jLabel6)
                .addContainerGap(198, Short.MAX_VALUE))
        );
        forcePanelLayout.setVerticalGroup(
            forcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forcePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Temperature Converter");

        javax.swing.GroupLayout temperaturePanelLayout = new javax.swing.GroupLayout(temperaturePanel);
        temperaturePanel.setLayout(temperaturePanelLayout);
        temperaturePanelLayout.setHorizontalGroup(
            temperaturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(temperaturePanelLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jLabel7)
                .addContainerGap(164, Short.MAX_VALUE))
        );
        temperaturePanelLayout.setVerticalGroup(
            temperaturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(temperaturePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Density Converter");

        javax.swing.GroupLayout densityPanelLayout = new javax.swing.GroupLayout(densityPanel);
        densityPanel.setLayout(densityPanelLayout);
        densityPanelLayout.setHorizontalGroup(
            densityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(densityPanelLayout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jLabel8)
                .addContainerGap(189, Short.MAX_VALUE))
        );
        densityPanelLayout.setVerticalGroup(
            densityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(densityPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Energy Converter");

        javax.swing.GroupLayout energyPanelLayout = new javax.swing.GroupLayout(energyPanel);
        energyPanel.setLayout(energyPanelLayout);
        energyPanelLayout.setHorizontalGroup(
            energyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(energyPanelLayout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        energyPanelLayout.setVerticalGroup(
            energyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(energyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayer(areaPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(volumePanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(weightPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lengthPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(speedPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(forcePanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(temperaturePanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(densityPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(energyPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(energyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(areaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(volumePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(weightPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lengthPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(speedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(forcePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(temperaturePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(densityPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(energyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(areaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(volumePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(weightPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lengthPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(speedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(forcePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(temperaturePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(densityPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(246, 246, 246)
                                .addComponent(appTitle))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLayeredPane1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(appTitle)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton6))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton5)
                    .addComponent(jButton8)
                    .addComponent(jButton9))
                .addGap(18, 18, 18)
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        lengthPanel.setVisible(true);
        areaPanel.setVisible(false);
        volumePanel.setVisible(false);
        weightPanel.setVisible(false);
        speedPanel.setVisible(false);
        forcePanel.setVisible(false);
        temperaturePanel.setVisible(false);
        densityPanel.setVisible(false);
        energyPanel.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        lengthPanel.setVisible(false);
        areaPanel.setVisible(true);
        volumePanel.setVisible(false);
        weightPanel.setVisible(false);
        speedPanel.setVisible(false);
        forcePanel.setVisible(false);
        temperaturePanel.setVisible(false);
        densityPanel.setVisible(false);
        energyPanel.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        lengthPanel.setVisible(false);
        areaPanel.setVisible(false);
        volumePanel.setVisible(true);
        weightPanel.setVisible(false);
        speedPanel.setVisible(false);
        forcePanel.setVisible(false);
        temperaturePanel.setVisible(false);
        densityPanel.setVisible(false);
        energyPanel.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        lengthPanel.setVisible(false);
        areaPanel.setVisible(false);
        volumePanel.setVisible(false);
        weightPanel.setVisible(true);
        speedPanel.setVisible(false);
        forcePanel.setVisible(false);
        temperaturePanel.setVisible(false);
        densityPanel.setVisible(false);
        energyPanel.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        lengthPanel.setVisible(false);
        areaPanel.setVisible(false);
        volumePanel.setVisible(false);
        weightPanel.setVisible(false);
        speedPanel.setVisible(true);
        forcePanel.setVisible(false);
        temperaturePanel.setVisible(false);
        densityPanel.setVisible(false);
        energyPanel.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        lengthPanel.setVisible(false);
        areaPanel.setVisible(false);
        volumePanel.setVisible(false);
        weightPanel.setVisible(false);
        speedPanel.setVisible(false);
        forcePanel.setVisible(true);
        temperaturePanel.setVisible(false);
        densityPanel.setVisible(false);
        energyPanel.setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        lengthPanel.setVisible(false);
        areaPanel.setVisible(false);
        volumePanel.setVisible(false);
        weightPanel.setVisible(false);
        speedPanel.setVisible(false);
        forcePanel.setVisible(false);
        temperaturePanel.setVisible(true);
        densityPanel.setVisible(false);
        energyPanel.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        lengthPanel.setVisible(false);
        areaPanel.setVisible(false);
        volumePanel.setVisible(false);
        weightPanel.setVisible(false);
        speedPanel.setVisible(false);
        forcePanel.setVisible(false);
        temperaturePanel.setVisible(false);
        densityPanel.setVisible(true);
        energyPanel.setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        lengthPanel.setVisible(false);
        areaPanel.setVisible(false);
        volumePanel.setVisible(false);
        weightPanel.setVisible(false);
        speedPanel.setVisible(false);
        forcePanel.setVisible(false);
        temperaturePanel.setVisible(false);
        densityPanel.setVisible(false);
        energyPanel.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void fromLengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromLengthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fromLengthActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
         try{
            //Converting Meters
            Double convertedLength;
            Double inputLength=Double.parseDouble(lengthInput.getText());
            if(fromLength.getSelectedItem().toString()=="Meters" && toLength.getSelectedItem().toString()=="Feet"){
            convertedLength=inputLength*3.28084;
            JOptionPane.showMessageDialog(this, "The Length in Feet is "+convertedLength.toString());
        }
            else if(fromLength.getSelectedItem().toString()=="Meters" && toLength.getSelectedItem().toString()=="Inches"){
            convertedLength=inputLength*39.37;
            JOptionPane.showMessageDialog(this, "The Length in Inches is "+convertedLength.toString());
        }
            else if(fromLength.getSelectedItem().toString()=="Meters" && toLength.getSelectedItem().toString()=="Centimeters"){
            convertedLength=inputLength*100;
            JOptionPane.showMessageDialog(this, "The Length in Centimeters is "+convertedLength.toString());
        }
            else if(fromLength.getSelectedItem().toString()=="Meters" && toLength.getSelectedItem().toString()=="Millimeters"){
            convertedLength=inputLength*1000;
            JOptionPane.showMessageDialog(this, "The Length in Millimeters is "+convertedLength.toString());
        }
            else if(fromLength.getSelectedItem().toString()=="Meters" && toLength.getSelectedItem().toString()=="Yards"){
            convertedLength=inputLength*1.094;
            JOptionPane.showMessageDialog(this, "The Length in Yards is "+convertedLength.toString());
        }
            
            //Converting Feet
            else if(fromLength.getSelectedItem().toString()=="Feet" && toLength.getSelectedItem().toString()=="Meters"){
            convertedLength=inputLength/3.28084;
            JOptionPane.showMessageDialog(this, "The Length in Meters is "+convertedLength.toString());
        }
            else if(fromLength.getSelectedItem().toString()=="Feet" && toLength.getSelectedItem().toString()=="Inches"){
            convertedLength=inputLength*12;
            JOptionPane.showMessageDialog(this, "The Length in Inches is "+convertedLength.toString());
        }
            else if(fromLength.getSelectedItem().toString()=="Feet" && toLength.getSelectedItem().toString()=="Centimeters"){
            convertedLength=inputLength*30.48;
            JOptionPane.showMessageDialog(this, "The Length in Centimeters is "+convertedLength.toString());
        }
            else if(fromLength.getSelectedItem().toString()=="Feet" && toLength.getSelectedItem().toString()=="Millimeters"){
            convertedLength=inputLength*305;
            JOptionPane.showMessageDialog(this, "The Length in Millimeters is "+convertedLength.toString());
        }
            else if(fromLength.getSelectedItem().toString()=="Feet" && toLength.getSelectedItem().toString()=="Yards"){
            convertedLength=inputLength/3;
            JOptionPane.showMessageDialog(this, "The Length in Yards is "+convertedLength.toString());
        }
            
            
            //Converting Inches
            else if(fromLength.getSelectedItem().toString()=="Inches" && toLength.getSelectedItem().toString()=="Meters"){
            convertedLength=inputLength/39.37;
            JOptionPane.showMessageDialog(this, "The Length in Meters is "+convertedLength.toString());
        }
            else if(fromLength.getSelectedItem().toString()=="Inches" && toLength.getSelectedItem().toString()=="Feet"){
            convertedLength=inputLength/12;
            JOptionPane.showMessageDialog(this, "The Length in Feet is "+convertedLength.toString());
        }
            else if(fromLength.getSelectedItem().toString()=="Inches" && toLength.getSelectedItem().toString()=="Centimeters"){
            convertedLength=inputLength*2.54;
            JOptionPane.showMessageDialog(this, "The Length in Centimeters is "+convertedLength.toString());
        }
            else if(fromLength.getSelectedItem().toString()=="Inches" && toLength.getSelectedItem().toString()=="Millimeters"){
            convertedLength=inputLength*25.4;
            JOptionPane.showMessageDialog(this, "The Length in Millimeters is "+convertedLength.toString());
        }
            else if(fromLength.getSelectedItem().toString()=="Inches" && toLength.getSelectedItem().toString()=="Yards"){
            convertedLength=inputLength/36;
            JOptionPane.showMessageDialog(this, "The Length in Yards is "+convertedLength.toString());
        }
            
            
            //Converting Centimeters
            else if(fromLength.getSelectedItem().toString()=="Centimeters" && toLength.getSelectedItem().toString()=="Meters"){
            convertedLength=inputLength/100;
            JOptionPane.showMessageDialog(this, "The Length in Meters is "+convertedLength.toString());
        }
            else if(fromLength.getSelectedItem().toString()=="Centimeters" && toLength.getSelectedItem().toString()=="Feet"){
            convertedLength=inputLength/30.48;
            JOptionPane.showMessageDialog(this, "The Length in Feet is "+convertedLength.toString());
        }
            else if(fromLength.getSelectedItem().toString()=="Centimeters" && toLength.getSelectedItem().toString()=="Inches"){
            convertedLength=inputLength/2.54;
            JOptionPane.showMessageDialog(this, "The Length in Inches is "+convertedLength.toString());
        }
            else if(fromLength.getSelectedItem().toString()=="Centimeters" && toLength.getSelectedItem().toString()=="Millimeters"){
            convertedLength=inputLength*10;
            JOptionPane.showMessageDialog(this, "The Length in Millimeters is "+convertedLength.toString());
        }
            else if(fromLength.getSelectedItem().toString()=="Centimeters" && toLength.getSelectedItem().toString()=="Yards"){
            convertedLength=inputLength/91.44;
            JOptionPane.showMessageDialog(this, "The Length in Yards is "+convertedLength.toString());
        }
            
            
            //Converting Millimeters
            else if(fromLength.getSelectedItem().toString()=="Millimeters" && toLength.getSelectedItem().toString()=="Meters"){
            convertedLength=inputLength/1000;
            JOptionPane.showMessageDialog(this, "The Length in Meters is "+convertedLength.toString());
        }
            else if(fromLength.getSelectedItem().toString()=="Millimeters" && toLength.getSelectedItem().toString()=="Centimeters"){
            convertedLength=inputLength*100;
            JOptionPane.showMessageDialog(this, "The Length in Centimeters is "+convertedLength.toString());
        }
            else if(fromLength.getSelectedItem().toString()=="Millimeters" && toLength.getSelectedItem().toString()=="Inches"){
            convertedLength=inputLength/25.4;
            JOptionPane.showMessageDialog(this, "The Length in Inches is "+convertedLength.toString());
        }
            else if(fromLength.getSelectedItem().toString()=="Millimeters" && toLength.getSelectedItem().toString()=="Feet"){
            convertedLength=inputLength/305;
            JOptionPane.showMessageDialog(this, "The Length in Feet is "+convertedLength.toString());
        }
            else if(fromLength.getSelectedItem().toString()=="Millimeters" && toLength.getSelectedItem().toString()=="Yards"){
            convertedLength=inputLength/914;
            JOptionPane.showMessageDialog(this, "The Length in Yards is "+convertedLength.toString());
        }
            
            //Converting Yards
            else if(fromLength.getSelectedItem().toString()=="Yards" && toLength.getSelectedItem().toString()=="Meters"){
            convertedLength=inputLength/1.094;
            JOptionPane.showMessageDialog(this, "The Length in Meters is "+convertedLength.toString());
        }
            else if(fromLength.getSelectedItem().toString()=="Yards" && toLength.getSelectedItem().toString()=="Centimeters"){
            convertedLength=inputLength*91.44;
            JOptionPane.showMessageDialog(this, "The Length in Centimeters is "+convertedLength.toString());
        }
            else if(fromLength.getSelectedItem().toString()=="Yards" && toLength.getSelectedItem().toString()=="Inches"){
            convertedLength=inputLength*36;
            JOptionPane.showMessageDialog(this, "The Length in Inches is "+convertedLength.toString());
        }
            else if(fromLength.getSelectedItem().toString()=="Yards" && toLength.getSelectedItem().toString()=="Feet"){
            convertedLength=inputLength*3;
            JOptionPane.showMessageDialog(this, "The Length in Feet is "+convertedLength.toString());
        }
            else if(fromLength.getSelectedItem().toString()=="Yards" && toLength.getSelectedItem().toString()=="Millimeters"){
            convertedLength=inputLength*914;
            JOptionPane.showMessageDialog(this, "The Length in Millimeters is "+convertedLength.toString());
        }
            
            
            else if(fromLength.getSelectedItem().toString()==toLength.getSelectedItem().toString()){
            JOptionPane.showMessageDialog(this, "Same units selected");
        }
    }
    catch(java.lang.NumberFormatException e){JOptionPane.showMessageDialog(this,"Only Numerical Input is Allowed");}
    
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appTitle;
    private javax.swing.JPanel areaPanel;
    private javax.swing.JPanel densityPanel;
    private javax.swing.JPanel energyPanel;
    private javax.swing.JPanel forcePanel;
    private javax.swing.JComboBox<String> fromLength;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lengthInput;
    private javax.swing.JPanel lengthPanel;
    private javax.swing.JPanel speedPanel;
    private javax.swing.JPanel temperaturePanel;
    private javax.swing.JComboBox<String> toLength;
    private javax.swing.JPanel volumePanel;
    private javax.swing.JPanel weightPanel;
    // End of variables declaration//GEN-END:variables
}
